### ISSUE TITLE
Rounding of raw data values and chart values

### ISSUE THREAD

**Issue by m-mohr** [sensebox/openSenseMap#100]
My sensor ( https://opensensemap.org/explore/578aad85ccff9d1000b7b638 ) is sending data with many digits after the decimal separator.
It might be a good idea to round the values on the OSM to some extent.
Also the chart is getting messy with these data. See the screenshot attached.
![screenshot 2016-07-17 01 58 43](https://cloud.githubusercontent.com/assets/8262166/16897909/850bac4a-4bc2-11e6-8de5-64fbae6b62da.png)

**Comment by mpfeil** [comment]
Also fixed and finally live
