### ISSUE TITLE
Function to search a senseBox

### ISSUE THREAD

**Issue by mariopesch** [sensebox/openSenseMap#102]
It would be nice to have a Search-Function in the Interface to search for a specific senseBox.

**Comment by chk1** [comment]
You can currently use the filter to search a box by name, maybe it's not too obvious

**Comment by dscso** [comment]
I've found there an JSON API:
`https://nominatim.openstreetmap.org/search/<query>?format=json`

**Comment by dscso** [comment]
Can I also ask what this does: https://github.com/sensebox/openSenseMap/blob/master/app/scripts/Control.Geocoder.js?

**Comment by chk1** [comment]
@dscso It's a Leaflet geocoder plugin. It lets you search for places, this was present earlier in osem but had some issues

![firefox_2016-10-21_21-11-18](https://cloud.githubusercontent.com/assets/828496/19608653/fccf4bfe-97d2-11e6-80a3-8efb423bf894.png)

**Comment by dscso** [comment]
Yes. I know what the code is for, but it doesn't work right? So what is the purpose?

**Comment by ubergesundheit** [comment]
It is currently not used.

**Comment by dscso** [comment]
Ah ok...

**Comment by mpfeil** [comment]
there will be a new search function when PR #139 will be merged

**Comment by mpfeil** [comment]
PR #139 is merged and will be online by the end of this week
