### ISSUE TITLE
Navbar on small displays

### ISSUE THREAD

**Issue by felixerdy** [sensebox/openSenseMap#103]
Map zoom controls and senseBox name are not completely visible on small displays, e.g. tablets

![unbenannt](https://cloud.githubusercontent.com/assets/12086004/16986142/5957ebac-4e85-11e6-84f8-7c16029d72d8.PNG)

**Comment by mpfeil** [comment]
fixed in 1f20a0345f2653433ac363c09d26ce1290d0f0d4
