### ISSUE TITLE
Filter Function not working given a Time Interval

### ISSUE THREAD

**Issue by SpeckiJ** [sensebox/openSenseMap#105]
The official Filter Function located in the "Filter Submenu" does not work given a Time Interval.

Steps to Reproduce the Issue:
1. Select Random Interval in Filter-Function on the official OpenSenseMap Site
2. apply Filter
3. Wait :)

After a considerable amount of Time the GET-Request fails and responds with HTTP Response Code 502.
There is **no** visual Feedback (besides inside the console log) indicating that the Request has failed. In the UI the User is still shown the loading Message of "Bitte warten, die Daten werden geladen...", albeit no Data being loaded anymore after the initial GET Request failed.

The Process can only be stopped by reloading the Site as the "reset Filter" Button is greyed out while a filter is being applied.

--------------------------------------------------------------------------------------------------------------
Auf der openSenseMap im Untermenü "Filter" funktioniert das filtern unter Angabe eines Zeitraumes nicht. 

Schritte zum Reproduzieren:

1. In der Filter Funktion der OpenSenseMap einen Zeitraum angeben
2. "Filter anwenden" drücken
3. Warten :)

Nach erheblicher (!) Wartezeit antwortet die API mit einem Http Response Code 502 und der GET-Request schlägt fehlt.
Es gibt **kein** visuelles Feedback (ausserhalb der Konsole) das anzeigt das der Request abgelehnt wurde und dem Nutzer wird weiter "Bitte warten, die Daten werden geladen..." angezeigt, obwohl keine Daten mehr geladen werden.
Der Prozess kann nur durch ein komplettes Neuladen der Seite gestoppt werden, da der "Filter zurücksetzen"-Button ausgegraut ist während gerade ein Filter angewendet wird.

**Comment by ubergesundheit** [comment]
Closed as of sensebox/openSenseMap-API#28
