### ISSUE TITLE
Filter mixes up markers 

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#112]
When applying a filter which requires an additional API request (like filtering for a timeframe), the map markers suddenly reference the wrong stations.

When clicking a marker the first time, the wrongly referenced station is opened.
Clicking it a second time, the correct _location_ is opened.

![screencast](https://cloud.githubusercontent.com/assets/7880552/18714748/1e884472-8017-11e6-961d-19830ef1fd4d.gif)

**Comment by mpfeil** [comment]
See @chk1 comment https://github.com/tombatossals/angular-leaflet-directive/issues/1041#issuecomment-221064809

While applying a filter the order of the array was not kept. 

Look at https://github.com/sensebox/openSenseMap/commit/82dd79ce22b03b86c2867c47c6a7fae2945b937a#diff-0ab943fb5b4c5d29e002cc88243db5b8R243 how it is solved right now.
