### ISSUE TITLE
Check Portuguese Translation

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#115]
Use the [english](https://github.com/sensebox/openSenseMap/blob/master/app/translations/en_US.json) or [german](https://github.com/sensebox/openSenseMap/blob/master/app/translations/de_DE.json) translations file to correct the [portuguese](https://github.com/sensebox/openSenseMap/blob/master/app/translations/pt_BR.json) translations for the openSenseMap.

**Comment by takecare** [comment]
confused by the deprecation notice on your readme. are you actively developing this?

**Comment by ubergesundheit** [comment]
Yeah this is actively developed. The notice is there because we want to rewrite the Frontend using vue. The translations will then be used in the new version

**Comment by takecare** [comment]
i can take a look at the `pt-br` translations and make sure they make sense and don't have any typos, but i'd feel more comfortable adding `pt-pt` translations. thoughts?

**Comment by mpfeil** [comment]
```pt-pt``` is also fine. Please rename the pt_BR.json file to pt_PT.json and add your translations. thanks for your help.

**Comment by marcelorl** [comment]
I completely can take pt-br. 
I'll give you a reply later. =)

**Comment by mpfeil** [comment]
@takecare @marcelorl checks ```pt-br```. so please create a new translation file for ```pt-pt```

**Comment by takecare** [comment]
👍

**Comment by nielsenmg** [comment]
Pull requested created for pt-br translation.

**Comment by murilodag** [comment]
Hello @ubergesundheit,

Is there anything else in this issue to be done?

**Comment by ubergesundheit** [comment]
This issue is from last year, but you could check if all translations are correct or you could check if all keys from english are present in portuguese.
