### ISSUE TITLE
Check Spanish Translations

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#117]
Use the [english](https://github.com/sensebox/openSenseMap/blob/master/app/translations/en_US.json) or [german](https://github.com/sensebox/openSenseMap/blob/master/app/translations/de_DE.json) translations file to correct the [spanish](https://github.com/sensebox/openSenseMap/blob/master/app/translations/es_CO.json) translations for the openSenseMap.

**Comment by ArkantosC** [comment]
I can help you with that.
