### ISSUE TITLE
missing api key during registration

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#143]
advancing to a next registration step by pressing `return` instead of clicking the button results in
- no orderID / apikey beeing generated
- map not displayed properly

I suppose `$scope.submit()` in register.js is not called, or `$scope.rc.sampleWizard.currentIndex` is not incremented properly

**Comment by mpfeil** [comment]
is fixed with this commit 98dc22720ca8468ba4edf66ea96e852905b85ea1

not deployed yet but soon
