### ISSUE TITLE
Translation of registration mail

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap#146]
Currently the registration mail is only available in German

**Comment by mpfeil** [comment]
@ubergesundheit can we change the default language to english? Right now if you choose a different language then english or german the registration mail is send in german

**Comment by ubergesundheit** [comment]
The mails are available in both german and english. I can change the default to english, registrations through the openSenseMap use the language present at registration

**Comment by mpfeil** [comment]
Right now if you choose spanish during the registration the mail is send in german. Would be better to send it in english.

**Comment by ubergesundheit** [comment]
fixed in api and mailer
