### ISSUE TITLE
Add compression to build process

### ISSUE THREAD

**Issue by mpfeil** [sensebox/openSenseMap#148]
### Expected Behavior
At the end of the build process create gzip compressed file.

With [latest release (0.9.4)](https://github.com/mholt/caddy/releases/tag/v0.9.4) of caddy it is possible to serve statically compressed .gz and .br files.

Check out [grunt-contrib-compress](https://github.com/gruntjs/grunt-contrib-compress)

### Actual Behavior
There is no compression. Its done on-the-fly by Caddy when website is requested.

**Comment by ubergesundheit** [comment]
So to make use of the precompressed files in caddy just remove the 'gzip' directive?

**Comment by mpfeil** [comment]
@ubergesundheit yes sir :squirrel:

tested it locally with a Caddyfile like this:
```
localhost:2020 {
	root dist_folder_of_build_process

	log stdout

	errors stdout

}
```
