### ISSUE TITLE
Visualization of mobile senseBoxes

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap#15]
If a SenseBox was registered as "mobile" the it should be (visually) separated from the fixed stations. Think about an initial position and an aggregation of the different measuring point, when clicking on it.

**Comment by chk1** [comment]
Just fyi, positions can be changed now, but there's no location history and no kind of historical visualization as of yet.

**Comment by mpfeil** [comment]
Finally online. thanks to @noerw
