### ISSUE TITLE
Interpolation (Power)

### ISSUE THREAD

**Issue by F1zZeR** [sensebox/openSenseMap#156]
### Expected Behavior
Use a Power of 9 and 10

### Actual Behavior
You can only use a Power of 1 to 8. 
At a Power of 9 and 10 there is an unknown error. With the advice to check the filter option.
(with no filter activated)

### Environment
- Browser & Version: Morzilla Firefox, Google Chrome, Opera

**Comment by ubergesundheit** [comment]
This is an error in the api. Related Issue: sensebox/openSenseMap-API#62
