### ISSUE TITLE
Old interpolations are not removed when changing phenomenon

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#161]
### Expected Behavior
Old interpolations are removed every time a new interpolation is requested

### Actual Behavior
Sometimes the old interpolation does not get removed and is displayed indefinetely on the map.

### Environment
- OS: Linux
- Browser & Version: Firefox 51.0.1

**Comment by jansule** [comment]
@ubergesundheit Interpolations are not removable anytime you leave the Interpolation view.
Example for reproduction: 
1. Go to Interpolation view 
2. Create new interpolation
3. Switch to Explore view
4. Switch back to Interpolation view

Interpolation cannot be removed anymore.
Also, `Create Interpolation` Button stays disabled.

**Comment by mpfeil** [comment]
Should be fixed right now.
