### ISSUE TITLE
time offset in data download

### ISSUE THREAD

**Issue by mpfeil** [sensebox/openSenseMap#168]
### Expected Behavior
Data should be downloaded for selected period of time.

### Actual Behavior
Right now there is a time offset of 1 hour.
![screenshot from 2017-03-17 10-06-15](https://cloud.githubusercontent.com/assets/2471172/24036363/8233510c-0af9-11e7-9ab7-c2e10351925c.png)

See selected `from-date` in frontend and `from-date` in Request URL

### Environment
- Browser & Version: Chromium: Version 57.0.2987.98 (64-bit)

**Comment by chk1** [comment]
Ist das vielleicht der Zeitzonenunterschied zu UTC? Ich weiß gerade nicht mehr genau, wie das Datum in der Datenbank gespeichert wird

**Comment by mpfeil** [comment]
Der `$http` Request im [download controller](https://github.com/sensebox/openSenseMap/blob/master/app/scripts/controllers/sidebar.download.js#L70) wechselt zu UTC und die Zeitverschiebung wird mit eingerechnet.

**Comment by ubergesundheit** [comment]
Alle Timestamps in der Datenbank sind UTC
