### ISSUE TITLE
add Information about Values and units

### ISSUE THREAD

**Issue by mariopesch** [sensebox/openSenseMap#189]
It would be nice to integrate some informations about the values and units of the measurements. For example informations about the UV-Index or limits for the fine particular sensors.

**Comment by mpfeil** [comment]
Please could you provide information and I am going to integrate them

**Comment by ubergesundheit** [comment]
For starters, you could display the values in the field `sensorType`

**Comment by synolus-david** [comment]
Maybe small information button for each value would be sufficient. If you click them you get a short Summary and maybe the option for more information. I provided an example for PM values in German which I copied from http://www.umweltbundesamt.de/themen/luft/luftschadstoffe/feinstaub.  

*Summary:*
Feinstaub besteht aus einem komplexen Gemisch fester und flüssiger Partikel und wird abhängig von deren Größe in unterschiedliche Fraktionen eingeteilt. Unterschieden werden PM10 (PM, particulate matter) mit einem maximalen Durchmesser von 10 Mikrometer (µm), PM2,5 und ultrafeine Partikel mit einem Durchmesser von weniger als 0,1 µm.

*More Information:*
Unter dem Begriff Feinstaub werden der primär emittierte und sekundär gebildete Feinstaub zusammengefasst. Primärer Feinstaub wird unmittelbar an der Quelle freigesetzt, zum Beispiel bei Verbrennungsprozessen. Entstehen die Partikel durch gasförmige Vorläufersubstanzen wie Schwefel- und Stickoxide und Ammoniak, so werden sie als sekundärer Feinstaub bezeichnet.
Emittenten

Feinstaub wird vor allem durch menschliches Handeln erzeugt: Primärer Feinstaub entsteht durch Emissionen aus Kraftfahrzeugen, Kraft- und Fernheizwerken, Öfen und Heizungen in Wohnhäusern, bei der Metall- und Stahlerzeugung oder auch beim Umschlagen von Schüttgütern. Er kann aber auch natürlichen Ursprungs sein (beispielsweise als Folge von Bodenerosion). In Ballungsgebieten ist der Straßenverkehr die dominierende Staubquelle. Dabei gelangt Feinstaub nicht nur aus Motoren – vorrangig aus Dieselmotoren – in die Luft, sondern auch durch Bremsen- und Reifenabrieb sowie durch die Aufwirbelung des Staubes von der Straßenoberfläche. Eine weitere wichtige Quelle ist die Landwirtschaft: Die Emissionen gasförmiger Vorläuferstoffe, insbesondere die Ammoniakemissionen aus der Tierhaltung, tragen zur sekundären Feinstaubbildung bei.
Gesundheitsrisiken

PM10 kann beim Menschen in die Nasenhöhle, PM2,5 bis in die Bronchien und Lungenbläschen und ultrafeine Partikel bis in das Lungengewebe und sogar in den Blutkreislauf eindringen. Je nach Größe und  Eindringtiefe der Teilchen sind die gesundheitlichen Wirkungen von Feinstaub verschieden. Sie reichen von Schleimhautreizungen und lokalen Entzündungen in der Luftröhre und den Bronchien oder den Lungenalveolen bis zu verstärkter Plaquebildung in den Blutgefäßen, einer erhöhten Thromboseneigung oder Veränderungen der Regulierungsfunktion des vegetativen Nervensystems (Herzfrequenzvariabilität).
Grenzwerte

Zum Schutz der menschlichen Gesundheit gelten seit dem 1. Januar 2005 europaweit Grenzwerte für die Feinstaubfraktion PM10. Der Tagesgrenzwert beträgt 50 µg/m3 und darf nicht öfter als 35mal im Jahr überschritten werden. Der zulässige Jahresmittelwert beträgt 40 µg/m3. Für die noch kleineren Partikel PM2,5 gilt seit 2008 europaweit ein Zielwert von 25 µg/m3 im Jahresmittel, der bereits seit dem 1. Januar 2010 eingehalten werden soll. Seit 1. Januar 2015 ist dieser Wert verbindlich einzuhalten und ab dem 1. Januar 2020 dürfen die PM2,5-Jahresmittelwerte den Wert von 20 µg/m3 nicht mehr überschreiten.

**Comment by synolus-david** [comment]
- [ ] Interpolation Text 
- [ ] Text Phenomena
