### ISSUE TITLE
changes of box text properties not properly persisted

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#190]
### Expected Behavior
- clearing a previously filled textfield should be saved
- the box url should be saved

### Actual Behavior
- the content of an optional text property (`grouptag`, `description`, `url`) remains, when it was cleared in the box editing dialog.

- the URL (`http://asdf.de`) is not saved at all

**Comment by ubergesundheit** [comment]
this is maybe an issue in the api?

**Comment by noerw** [comment]
indeed.

**Comment by ubergesundheit** [comment]
Using this for discussion:
I think we shouldn't reanimate the `weblink` property of the boxes. What if someone sets a link to illegal or unpleasant content? If we support this kind of urls, clicking them should clearly state that we are not responsible for the content and so on.

thoghts @mpfeil ?

**Comment by mpfeil** [comment]
Maybe by clicking the weblink we state `you are leaving openSenseMap and we are not responsible of the content. do you want to continue? yes or no.`

**Comment by robarto** [comment]
@mpPfeil suggestion seems fine for me.
