### ISSUE TITLE
Filter broken after `reset filters`

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#196]
### Expected Behavior
Filtering  - eg. for a time window - should always work when clicking `apply filter`.

### Actual Behavior
Once `reset filters` was pressed, all filter values seem to be replaced with `''`. The next `apply filter` call submits those to the API:
```
/boxes?date=2017-07-16T12:55:36.200Z,2017-07-17T12:55:36.200Z&exposure=&grouptag=&phenomenon=
```
The API disregards given, but empty parameters with `UnprocessableEntity` errors.

### Environment
- OS: Ubuntu 16
- Browser & Version: FF55

**Comment by ubergesundheit** [comment]
I think this should be fixed in the api.
