### ISSUE TITLE
Deactivate Extension tab in edit mode for custom senseBoxes

### ISSUE THREAD

**Issue by mpfeil** [sensebox/openSenseMap#207]
### Expected Behavior
It is not possible to activate an extension for a custom senseBox. Deactive extension tab in edit mode for custom senseBoxes

### Actual Behavior
You can activate an extension and save it but nothing happens

**Comment by noerw** [comment]
Additionally, for a box that was registered with an extension, the checkbox is disabled (eg. cannot be clicked).

**Comment by mpfeil** [comment]
The checkbox is disabled because it is not possible to deactivate an extension after it was activated once
