### ISSUE TITLE
Allow users to specify language in url

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#212]
Suggestion from Chat:

Make it possible to specify the language through a parameter in the url

**Comment by mpfeil** [comment]
Behavior now:
- if your not logged in and enter opensensemap.org the first time: the browser language is looked up and the language is changed to it
- if your not logged in and change the language: the selected language is stored to the `localstorage`
- if your not logged in and visit opensensemap.org again: stored language from `localstorage` is read and the language is changed to it
- if you log in: the language is changed to your stored language at `User -> Settings`
- if you are logged in and change the language: the language is just changed temporarily
