### ISSUE TITLE
Not Reproducible for now: Frontend requests timestamps from the future on Windows 7

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#237]
### Expected Behavior
After clicking one of the buttons "Last 24 hours" "Last Week" or "Last Month" the graphs should display the data for the requested timeframe

### Actual Behavior
The graphs show an error (Common_error)

The response from the server says that the requested timestamp is in the future. I suspect something with daylight saving.

### Environment
- OS: Windows 7
- Browser & Version: Firefox 56.0.2 / IE

**Comment by ubergesundheit** [comment]
Reproducible on browserling. But the clock seems wrong there anyway. Need to find a physical machine with windows 7

**Comment by Adorfer** [comment]
same goes for FF56.0.2 on W10 on at least 3 different machines. 
VM on window10 can be provided on short delay upon request for debugging. 

Perhaps linked: Click on "last week" runs into trouble about 90% of the time too: 

![grafik](https://user-images.githubusercontent.com/10302493/32447133-6f495a3a-c30b-11e7-8297-d5571019824f.png)

if i select it manually, it works: 
![grafik](https://user-images.githubusercontent.com/10302493/32447177-97de7e08-c30b-11e7-8d6e-3032e1976ff5.png)

**Comment by ubergesundheit** [comment]
What does https://time.is on your machine say?
For example for me it says:
```
Your time is exact!
The difference from Time.is was -0.008 seconds (±0.022 seconds).
```

**Comment by Adorfer** [comment]
> "Deine Uhr geht 2,8 Sekunden vor."

this may cause an issue?

**Comment by Adorfer** [comment]
o.k. that's it! changing from windows-default ("tz.microsoft.com?" to "de.pool.ntp.org") resolves the issue. 

![grafik](https://user-images.githubusercontent.com/10302493/32449002-b97b5928-c310-11e7-87a7-c4ba3dd9eba9.png)

Nevertheless, since this requires admin properties to the system and many users may be challenged doing so, perhaps make the code on the opensensemap-api more robust, not failing if the "end" timestamp is (slightly) in the future.

**Comment by ubergesundheit** [comment]
Thank you very much for testing this! The restriction is in the api to prevent submitting values with time stamps in the future. I guess for retrieving data dates in the future should be possible.

Thanks again for investigating! I’ll reopen a new issue in the api repository
