### ISSUE TITLE
show sensor-id in settings

### ISSUE THREAD

**Issue by Adorfer** [sensebox/openSenseMap#243]
it is obvious that the URL of a sensor contains its ID, 
But I would prefer to have it written in the settings "on the page" too. 
just for Cut&Paste purposes. Or 'printing'

**Comment by mpfeil** [comment]
Right now in the editing section of a senseBox under sensors you should find the sensor ID.
![screenshot from 2018-01-31 15-42-05](https://user-images.githubusercontent.com/2471172/35628928-97255d3a-069d-11e8-95ec-62d4daf47924.png)
