### ISSUE TITLE
fetch mobile box trajectory for default time frame

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#249]
### Expected Behavior
Selecting a sensor for mobile boxes should show the trajectory for the same timeframe as the measurements.

### Actual Behavior
Trajectory is fetched without time parameters.
As of now, [this box](https://opensensemap.org/explore/5a158c5c19991f00113af4df) showcases the issue.

This is a regression of https://github.com/sensebox/openSenseMap/commit/0b03d6798f3059345cc74a49cd15e4f8b17e0f5a / a followup for #234.
Maybe the [`performFilter()` function](https://github.com/sensebox/openSenseMap/blob/0b03d6798f3059345cc74a49cd15e4f8b17e0f5a/app/scripts/controllers/sidebar.boxdetails.js#L182-L195) can be reused in `selectSensor()`?

**Comment by mpfeil** [comment]
If you select a `mobile` senseBox we are not going to show the trajectory. We will add an info that you have to select a `sensor` to get the trajectory.
