### ISSUE TITLE
Show direct download URL for data download for power users.

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#255]
### Expected Behavior
As power user, I want to see the URL of the request for data download and descriptive statistics, so I can take the request and firther modify the parameters for example to use in curl or other http clients

### Actual Behavior
Clicking the "Download" Buttons opens a new window, the request URL is never directly visible

**Comment by noerw** [comment]
To avoid clutter in the download section, I would hide this information together with column selection and data format in an "advanced options" panel

**Comment by ubergesundheit** [comment]
It doesn't even need to be that complicated. Just change the button with click listener to a simple <a> tag with the correct href attribute so I can right click and select 'Copy Link Location`
