### ISSUE TITLE
usability enhancements

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#258]
Some opinionated suggestions, that would improve usability:

### header
- [x] auto focus login text fields
- [x] collapse responsive header drop down when clicking on things
- [x] hide language selector when logged in

### box details
- [x] show box description as multi line text (render linebreaks)
- [x] click on refresh badge: instant refresh
- [x] "edit box" button in boxdetails when logged in

### data download
- [x] "Mittelwerte" is confusing, rename to 'Aggregate to..' / 'Gruppieren nach..'?
- [ ] ~remove unused dataformat "CSV" option from data download~
- [x] provide alternative formats (see API https://github.com/sensebox/openSenseMap-API/issues/145)
- [x] hide download columns & alternative formats in collapsible "advanced options" panel

### misc
- [ ] when adding a sensor: auto completion / search results for existing values, to avoid misspelled duplicates (`phenomenon`, `unit`, `type`)

**Comment by ubergesundheit** [comment]
> remove unused dataformat "CSV" option from data download

We will eventually add more data encodings (like json)

**Comment by mpfeil** [comment]
> hide language selector when logged in

Right now i will leave it like it is. But I know that the selector is disturbing and annoying.
@robarto @ubergesundheit maybe we should discuss if we want to keep all languages or if we remove all languages except for german and english.

BTW: these both are up to date and the rest is not taken care of.

**Comment by ubergesundheit** [comment]
Maintaining the german and english translations is already a really time-consuming task, so I am very much in favor of only supporting these two languages.

Lets consider just the work needed to add and maintain a new language:
- Creating the files
- Translating all the terms
- Making sure the terms are about as long as the original string (so the visual layout looks the same)
- Adding translations of new terms along the way as development progresses

Plus: We only speak german and english. In my opinion, adding machine translated content should be avoided

**Comment by mpfeil** [comment]
Also deployed with version 2.0.0
