### ISSUE TITLE
All texts missing whitespace

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap#261]
### Expected Behavior
Text should be displayed with whitespace

### Actual Behavior
No spaces are displayed

![no_spaces_chromium](https://user-images.githubusercontent.com/1494211/36246528-8dbf46b8-1230-11e8-81ca-139ceff447b5.png)

### Environment
Version 64.0.3282.140 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by mpfeil** [comment]
Have the same version and its working.
