### ISSUE TITLE
Sensordaten werden nicht aktualisiert

### ISSUE THREAD

**Issue by FlorianWesselss** [sensebox/openSenseMap#265]
### Expected Behavior
Die Daten sollten sich jede Minute aktualisieren

### Actual Behavior
Alle sensoren unter dem Sensor, der noch nichts gemessen hat, werden nicht aktualiesiert

### Environment
- OS: Windows 10
- Browser & Version: Firefox Quantum 58.0.2 (64-Bit)

**Comment by robarto** [comment]
da ist ein hotfix nötig!
