### ISSUE TITLE
Automatic sensor filtering in the datadownload 

### ISSUE THREAD

**Issue by mariopesch** [sensebox/openSenseMap#267]
### Expected Behavior

When you go to the datadownload and select a part of a map with senseBoxes only the sensors of the actual boxes should be displayed in the dropdown menu.

### Actual Behavior

When you go to the Datadownload and select a part of a map with senseBoxes all sensors of all boxes will be displayed in the dropdown menu and makes it hard to find the right one. Otherwise you always have to filter the senseBoxes first and then go to the datadownload

### Environment
- OS: MacOS/Windows/
- Browser & Version: Chrome

**Comment by synolus-david** [comment]
![grafik](https://user-images.githubusercontent.com/21102823/39623134-f04c28e0-4f94-11e8-9a2e-197914e783e5.png)

Additional RemarK. Filter function is not working when using " MS Internet Explorer"...
