### ISSUE TITLE
Selecting last month for sensor data give last week

### ISSUE THREAD

**Issue by tilomat** [sensebox/openSenseMap#268]
### Expected Behavior

when I selected last month for a given data chart, I should get all data for the last month

### Actual Behavior

the explicit timeframe is updated on the top section, however, the chart only displays data from last week.

### Environment
- OS: mac OSX high sierra 10.13.4
- Browser & Version: chrome 66.0.3359.170

**Comment by mpfeil** [comment]
Hi @tilomat 
the actual behavior is a bit confusing. Right now the used api route for displaying the chart data (https://docs.opensensemap.org/#api-Measurements-getData) is just returning `10000` data points thats why in most cases you just see the last week.

We are changing and adapting the API right now. Please see Issue https://github.com/sensebox/openSenseMap-API/issues/114
