### ISSUE TITLE
OpenSenseMap takes 8 to ∞ seconds to load

### ISSUE THREAD

**Issue by LuchtwachtersDelft** [sensebox/openSenseMap#283]
### Expected Behavior

I type in opensensemap.org and this pops up in under 1 second. Just like any maps site.

![image](https://user-images.githubusercontent.com/37801654/47015947-a7f05580-d14e-11e8-90f8-d91fcd709ff5.png)

### Actual Behavior

I type in opensensemap.org and this blank map shows for 8 to 27 seconds.

![image](https://user-images.githubusercontent.com/37801654/47016039-e554e300-d14e-11e8-9c37-59d2d4732f20.png)

Especially for new participants that gives a really bad first impression. They just want to register their new sensor, but they have to wait more than 8 seconds to even be able to interact with the page. Depending on the device they might not see the completion of the page at all, as it runs out of RAM or patience. You read that right. Android will show a warning that the page has stalled and suggests to close it.

What is actually going on?

![image](https://user-images.githubusercontent.com/37801654/47016137-1a613580-d14f-11e8-809d-d103bf6bee5c.png)

In some cases /boxes is taking 27 seconds to download. What is in there?

![image](https://user-images.githubusercontent.com/37801654/47016289-89d72500-d14f-11e8-9400-5e0791149f13.png)

Looks like the data of all 2396 sensors. Do we really need all that data at once?

Aside from downloading /boxes most of the time is spent on scripting.

![image](https://user-images.githubusercontent.com/37801654/47016456-0538d680-d150-11e8-890a-7652357d5840.png)

The script is clustering sensors by location to generate a map. Is it really important to show a really accurate real-time map of all clusters on the home page? Can't we cache the global map for a few minutes on the server? Maybe there are some ways to optimize the scripts?

### Environment
- OS: All of them
- Browser & Version: Yes

**Comment by mpfeil** [comment]
Hi @LuchtwachtersDelft 

we are aware of that issue and are working on it. You can checkout the following PR https://github.com/sensebox/openSenseMap-API/pull/164.

A preview can be found at https://testing.opensensemap.org

If you have any suggestions for optimizing the scripts we would really appreciate your help.
There is some kind of caching already implemented in the https://github.com/sensebox/openSenseMap-API

**Comment by LuchtwachtersDelft** [comment]
Great! I will try to contribute.

**Comment by chk1** [comment]
There should be a background color within the circles, the number is hard to read if it gets placed on top of place names

![image](https://user-images.githubusercontent.com/828496/47443377-7281e280-d7b4-11e8-8e2f-15a05dbb5aca.png)

**Comment by LuchtwachtersDelft** [comment]
The testing version loads instantaneously, which is amazing!

... Until I Ctrl+F5'ed to purge the browser cache and refresh the page.

Then this happened.

![image](https://user-images.githubusercontent.com/37801654/47531664-90337280-d8ae-11e8-916b-92ffa61a6609.png)

![image](https://user-images.githubusercontent.com/37801654/47531740-c40e9800-d8ae-11e8-889f-b2715cfe1787.png)

**Comment by noerw** [comment]
Hi @LuchtwachtersDelft, this is because of a different configuration of the background map in the testing environment, it won't affect the main environment.

**Comment by mpfeil** [comment]
New version is deployed in production.

**Comment by LuchtwachtersDelft** [comment]
Fantastic! 

Say, is there a way to make the browser get the new version of the site? Because I had to manually force refresh.

**Comment by mpfeil** [comment]
We some kind of issues before and we thought we found a solution. But I am going to test it again. So for now please force a full refresh.

**Comment by robarto** [comment]
Yes! So proud that it finally happened!
