### ISSUE TITLE
Inaktive Marker when senseBox is online

### ISSUE THREAD

**Issue by felixerdy** [sensebox/openSenseMap#285]
### Expected Behavior
Marker should be green when senseBox is sending live data

### Actual Behavior
Sometimes the marker is grey even though the senseBox is sending live data

## Examples:
|https://opensensemap.org/explore/5710de1a45fd40c8198ccece|https://opensensemap.org/explore/58932c89d038b000102f7d35|
|-|-|
|<img width="1792" alt="bildschirmfoto 2018-11-23 um 12 42 12" src="https://user-images.githubusercontent.com/12086004/48941826-6311c880-ef1d-11e8-93a0-9fa29034d50d.png">|<img width="1792" alt="bildschirmfoto 2018-11-23 um 12 42 44" src="https://user-images.githubusercontent.com/12086004/48941830-65742280-ef1d-11e8-9d30-ccbc546a3035.png">|

__Note:__ This only occurs sometime

### Environment
- OS: macOS 10.14.1
- Browser & Version: Google Chrome 70.0.3538.102

**Comment by mpfeil** [comment]
This is now fixed with the new version of API.
