### ISSUE TITLE
Changes of box texts are not saved

### ISSUE THREAD

**Issue by thjean** [sensebox/openSenseMap#286]
The (e.g. description text) of an exisiting box on the 'general' page can be edited, but the change is not persistently saved.  

Furthermore, when reloading the 'edit/general' page, the hourglass pops up, "Fetching boxes and measurements" is displayed and the page freezes. 

Observed with Firefox, Chrome and Edge on Windows7 and Windows10

**Comment by mpfeil** [comment]
Hi @thjean,

thanks for reporting. We will try to fix it as soon as possible and release a new fix in the next days.
