### ISSUE TITLE
E-mail in spam folder

### ISSUE THREAD

**Issue by LuchtwachtersDelft** [sensebox/openSenseMap#287]
### Expected Behavior

E-mails from sensebox.de go to inbox.

### Actual Behavior

E-mails from sensebox.de disappear in spam / junk / promotional / newsletter folder.

### Environment

At least hotmail.com.

During multiple workshops I have noticed the users get stuck after registration, because they do not get any e-mails in their inbox. Instead they are blocked or moved to the spam folder, which does not pop-up a notification.

Surprisingly X-Spam-Status is 2.6 out of 4.0 and DKIM_SIGNED, DKIM-VALID, and SPF_PASS. So I am not sure why hotmail and possibly other e-mail providers are flagging sensebox.de e-mails.

**Comment by mpfeil** [comment]
Hi @LuchtwachtersDelft,

thanks for your feedback. I am going to forward it internally to the person in charge.
Beside that I am going to close this issue because it is not an issue with the frontend and is not part of this repository.
