### ISSUE TITLE
senseBox 5c7862b2973d19001a6163b5 not active but data is fresh

### ISSUE THREAD

**Issue by catfish34** [sensebox/openSenseMap#294]
Hi all. I created custom senseBox:
https://opensensemap.org/explore/5c7862b2973d19001a6163b5
Looks like everything is good. But color is not green. Looks like it is not active? I cannot understand why.

### Environment
- OS: Win 10
- Browser: Chrome

**Comment by mpfeil** [comment]
HI @catfish34,

thanks for reporting. Should be fixed if this issue is resolved: 
https://github.com/sensebox/openSenseMap-API/issues/177

**Comment by catfish34** [comment]
ok. Thanks.

**Comment by mpfeil** [comment]
Hi @catfish34,

we have deployed the new verison of the API and your box is now active (`green` marker).
