### ISSUE TITLE
Credentials in config page are osem logindata as default

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap#295]
### Expected Behavior
There is a new feature available in the front end to integrate WiFi credentials into the sketch. 
You can type in your access data in two empty fields.
### Actual Behavior
The input fields for SSID and Password are already filled with mailaddress and password of osem login. This might have happend because I selected that I want to store the login data when loggin in to osem before.

Chrome Version 72.0.3626.121 (Offizieller Build) (64-Bit)

**Comment by mpfeil** [comment]
@janwirwahn please test on https://deploy-preview-301--determined-easley-6acd12.netlify.com/
