### ISSUE TITLE
sensebox:home accordion should be collapsed in registration

### ISSUE THREAD

**Issue by robarto** [sensebox/openSenseMap#296]
### Expected Behavior
all types of senseBox hardware accordions should be collapsed, to avoid the focus on home for edu users. 

### Actual Behavior
senseBox:home accordion is uncollapsed. on a normal screen the other types are not visible and users tend to click on the senseBox MCU, scroll down and go to the next screen...

### Environment
independent

**Comment by mpfeil** [comment]
@robarto check it out here https://5c9a5e5b2486250008813d4a--determined-easley-6acd12.netlify.com/
