### ISSUE TITLE
'Copy to Clipboard' for IDs not working

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap#297]
### Expected Behavior
I wanted to copy the IDs from one of my senseBoxes. 

### Actual Behavior
On Dashboard page: if you press the button for copying senseBox ID to clipboard there is nothing returned when trying to insert. Same problem for copying sensor IDs from a specific senseBox

### Environment
- Ubuntu 16.04 LTS (64-bit)
- Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by mpfeil** [comment]
@janwirwahn please check the fix here: https://deploy-preview-303--determined-easley-6acd12.netlify.com/
