### ISSUE TITLE
Slow server response

### ISSUE THREAD

**Issue by thjean** [sensebox/openSenseMap#311]
### Expected Behavior
Fast(er) server responses when posting or viewing data.

### Actual Behavior
Since a couple of days, I observe changing - but generally very slow - server response times. This concerns posting to api.opensensemap.org as well as displaying data ("please wait, loading data ...".
While connecting times to api.opensensemap.org are unchanged (below 1 sec for https-connects on an ESP32 and less than 30ms for http connects), the server takes up to 50-60 secs to answer the POST. Response-Time as indicated in the server header answer goes up to 40000 and more. The api-server response used to be well below 1 sec a week or two ago. There is no difference when posting via https to api.opensensemap.org or http to ingress.opensensemap.org. From time to time the server answers "HTTP/1.1 502 Bad Gateway".

Is there currently a problem with data storage? 

### Environment
- ESP32 and ESP8266 posting multiple new measurements as JSON-objects
- OS: Windows 7
- Browser & Version: Firefox 66.0.3, Chrome 73.0.3683.103

**Comment by ubergesundheit** [comment]
Thank you for opening this issue. The site is indeed experiencing some issues with too much load. This is actively worked on!

**Comment by mpfeil** [comment]
This should be fixed. Going to close this issue.
