### ISSUE TITLE
Posting multiple new measurements for the same sensor

### ISSUE THREAD

**Issue by thjean** [sensebox/openSenseMap#313]
Unsure if this is related to the GUI or to the API...

### Expected Behavior
Posting a JSON object containing multiple new measurements with different values and createdAt-timestamps for the same sensorID should be possible. 

### Actual Behavior
When a JSON object contains several new measurements for the same sensorID with different ["value", "createdAt"] entries, the posting is accepted by the api, however it seems that just the value with the most recent timestamp is considered. Viewing the sensor data in opensensemap.org just displays the value with the most recent timestamp instead of showing all values of the JSON object.

The expectation is probably due to my misunderstanding of the api-doc as #64 mentions different sensorIDs, however it would be beneficial for lowpower sensors collecting data and posting multiple sensor measurement data for the same sensorID in a single posting.

**Comment by noerw** [comment]
There are multiple formats available, as documented [here](https://docs.opensensemap.org/#api-Measurements-postNewMeasurements) (end of the section provides examples for each format).

The JSON-object format can only accept one value per sensor ID (this is a limitation of the JSON encoding, as object keys need to be unique).
Instead you could use the JSON Array format:
```json
[
  {"sensor":"sensorID", "value":"value"},
  {"sensor":"anotherSensorId", "value":"value", "createdAt": "RFC 3339-timestamp", "location": [lng,lat,height]}
  ...
]
```

**Comment by thjean** [comment]
Thank you for the explanation and for the link to the format description. Posting multiple sensors within one JSON-object works fine as described, my issue was related to having multiple values per sensorID. I understand that this is a JSON restriction. 

Does your hint "_Instead you could use the CSV or JSON Array formats:_" mean that using another format (like CSV or JSON Array or senseBox raw format) would allow me to send a  bunch of values for one sensorID with different timestamps within one posting or does the same restriction apply for all formats?

**Comment by noerw** [comment]
Exactly, the other formats support your use case, just not the *JSON-Object* format.

**Comment by thjean** [comment]
Thanks a lot!

**Comment by thjean** [comment]
Sorry for re-opening the issue.
My use case works pretty well when using the JSON-Array or CSV format, however I do not manage to get the raw format "application/snsbx-bytes-ts" working. Posting 20 bytes (or a multiple of 20 bytes) payload as described (12 Bytes sensorID, float value and uint32_t timestamp) always results in a server error "HTTP/1.1 415 Unsupported Media Type" saying "{"code":"UnsupportedMediaType","message":"Unsupported content-type."}".
Before I start investigating more effort in bug-hunting, I would like to double-check that the content-type "application/snsbx-bytes-ts" is really implemented and functional?

**Comment by noerw** [comment]
Good catch!
[Looking at the code](https://github.com/sensebox/openSenseMap-API/blob/316e3e77025a17044d35bab74e4d44aa7bd2db14/packages/models/src/measurement/decoding/index.js#L20-L23), the documentation is indeed wrong.
The correct `Content-Type` header value would be `sbx-bytes-ts`.

**Comment by thjean** [comment]
Great! 
Can confirm that changing the content type to "application/sbx-bytes-ts" makes RAW format working like a charm.

**Comment by ubergesundheit** [comment]
Never thought seeing someone use the byte format in the wild! :)

**Comment by thjean** [comment]
The byte format looked like a promising workaround for the current response time issue. As I experienced data loss due to response times that were partially longer than the measurement period, I implemented a post message queue and found the byte format to be best suited with regards to memory usage. This works fine, the only small drawback is the decimal place given by the api and not by the user.

**Comment by ubergesundheit** [comment]
The post message queue sounds interesting! Is your code open source somewhere?

**Comment by thjean** [comment]
The code is a quick hack, lots of hardcoded stuff, so it is not ready to be published on git.
The message queue is currently implemented in a very simple and straight forward way:
When a measurement cycle is done, the entire data part of the message is stored in a buffer. Another periodic task checks the buffer, builds the message header, appends the data and tries posting. Once the posting is successful (got a 201 response from the server), the queued data are marked as posted, else the task retries the posting. If a new measurement data gets available before the previous posting is successful, the buffer fills up and the use case of having multiple data for the same sensor in one posting request comes up. On the ESP32 using FreeRTOS, this approach is quite simple. I will now start thinking about an implementation on the ESP8266, where the available memory is getting an issue when using https.

**Comment by ubergesundheit** [comment]
Looking forward to see the code :)
