### ISSUE TITLE
SVG Favicon not supported

### ISSUE THREAD

**Issue by LuchtwachtersDelft** [sensebox/openSenseMap#314]
opensensemap.org has a favicon, but it's an SVG. Some browsers don't support SVG favicons, see:

https://caniuse.com/#feat=link-icon-svg

Browsers that don't support SVG favicon show a generic icon, which makes it hard to find tabs that contain openSenseMap pages.

You can use for example https://realfavicongenerator.net/ to generate the suitable variants of favicons for different browsers and devices as well as the HTML or Grunt.

![image](https://user-images.githubusercontent.com/37801654/57989480-684e6b00-7a9b-11e9-9b0e-844861f9e0cb.png)

![image](https://user-images.githubusercontent.com/37801654/57989495-aba8d980-7a9b-11e9-8169-baa428eee41b.png)

**Comment by ubergesundheit** [comment]
Check out https://realfavicongenerator.net/favicon_checker?protocol=https&site=opensensemap.org
