### ISSUE TITLE
luftdaten BME280 pressure wrong

### ISSUE THREAD

**Issue by jordanc365** [sensebox/openSenseMap#318]
Hello,
Pressure data reported from luftdaten sensors with a BME280 attached report pressure incorrectly and is off by a factor of 100.
Mine currently reads: 102776.13Pa 
But should be: 1027.7613
Thanks!

**Comment by ubergesundheit** [comment]
Hi @jordanc365 

the Luftdaten devices are configured to send atmospheric pressure in pascal while senseBox devices are configured to send atmospheric pressure in hectopascal where 100 pascal = 1 hectopascal. 

https://en.wikipedia.org/wiki/Pascal_(unit)#Hectopascal_and_millibar_units
