### ISSUE TITLE
group label is not saved after regristration of a new sensebox 

### ISSUE THREAD

**Issue by synolus-david** [sensebox/openSenseMap#319]
### Expected Behavior

group label should be saved after regristration of a new sensebox 
### Actual Behavior

group label is not saved after regristration of a new sensebox 

### Environment
- Language: German
- Tested "Gruppenkennzeichnung" Kxxx-Sxxx
- OS: Windows 10
- Browser & Version: firefox

**Comment by ubergesundheit** [comment]
This seems to work on testing...

**Comment by umut0** [comment]
Problem seems to be that the "Gruppenkennzeichnung" field gets cleared when you select one of the Menus in the "Erweitert" Section, e.g. MQTT or TTN.

**Comment by ubergesundheit** [comment]
Should be fixed on opensensemap.org
