### ISSUE TITLE
`grunt serve` fails

### ISSUE THREAD

**Issue by noerw** [sensebox/openSenseMap#322]
### Expected Behavior
development server should work when following installation instructions

### Actual Behavior
The build from the live server fails, as leaflet (`window.L`) is not loaded in the page.
During the `bowerInstall:app` grunt task started via `grunt serve` the following message appears:
```
Running "bowerInstall:app" (bowerInstall) task
app/index.html modified.

leaflet was not injected in your file.
Please go take a look in "app/bower_components/leaflet" for the file you need, then manually include it in your file.
```

This error occured since clearing the `app/bower_components` folder. Before the problem, bower installed leaflet v1.3.4., now leaflet 1.5.1 was fetched.

### Environment
bower 1.8.8

**Comment by ubergesundheit** [comment]
Does https://github.com/sensebox/openSenseMap/commit/709ddf4755f3cb041fbdeee7d277c03db5a04f43 fix your issue?

**Comment by noerw** [comment]
yes, although i'm not sure why that fixes it :D
