### ISSUE TITLE
Dead link to sensebox documentation

### ISSUE THREAD

**Issue by philippmaurer** [sensebox/openSenseMap#323]
**Description**
The link from the account overview ( https://opensensemap.org/account ) to "https://sensebox.de/de/books" labeled "Documentation" does lead to a 404 page.

![grafik](https://user-images.githubusercontent.com/10925094/67405190-b6b8e600-f5b4-11e9-9247-3df996b2b7f7.png)

**Comment by mpfeil** [comment]
This is fixed with new deployment `2.2.1-c7fe3a6`
