### ISSUE TITLE
Add apple-touch-icon

### ISSUE THREAD

**Issue by nasendackel** [sensebox/openSenseMap#339]
Because there is no native app for macOS or iOS, please add a apple-touch-icon-precomposed. 

[Configuring Web Applications](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

### Environment
- OS: iOS, macOS
- Browser & Version: Safari

**Comment by ubergesundheit** [comment]
This should work now.
