### ISSUE TITLE
Show Sensortype besides the phenomena in the overview

### ISSUE THREAD

**Issue by mariopesch** [sensebox/openSenseMap#340]
### Expected Behavior
Show not only the Phenomena in the overview but also the sensor type. 
Example:
When using Temperatur from the HDC1080 and the BMP280 at the same time it is not clear which ID belongs to which Sensor

![image](https://user-images.githubusercontent.com/7090577/74729515-e1eed180-5244-11ea-821b-e3da9763b6aa.png)

## Actual Behavior

Only show phenomena and the corresponding ID's

**Comment by ubergesundheit** [comment]
Fixed once #341 is deployed in production

**Comment by ubergesundheit** [comment]
@mariopesch Fix should be live on opensensemap.org
