### ISSUE TITLE
Website and API offline

### ISSUE THREAD

**Issue by marcelreppi** [sensebox/openSenseMap#347]
Hey,

in the past few days I wasn't able to reach the website or access the API.
When is it coming back?

Best regards
Marcel

**Comment by mpfeil** [comment]
Hi @marcelreppi ,

for me everything is working and is operational. You can check status.sensebox.de

Have you got any error?

**Comment by marcelreppi** [comment]
No, there are no errors.
I have just restarted my router and reconnected my laptop to the internet and everything seems to working again. I don't know what happened.
Sorry to bother and thank you very much for the quick response!
