### ISSUE TITLE
Air Pressure is showing up wrong - factor 10x higher

### ISSUE THREAD

**Issue by offlinehoster** [sensebox/openSenseMap#350]
### Actual Behavior

The airpressure is not displayed correctly.

https://opensensemap.org/explore/5ecb90bcd0545b001c90f3d6

It says

101977.88 hPa instead of 1019.77.88 hPa

The sensor itself shows it up correctly on its config site (luftdaten.info)

Any ideas how to fix this?

**Comment by ubergesundheit** [comment]
This an error on our side: Usually, our devices send air pressure in hPa, luftdaten.info devices send in Pa. So we blindly assume hPa.

You could go to https://opensensemap.org/account/5ecb90bcd0545b001c90f3d6/edit/sensors and manually change the unit of your air pressure sensor.
