### ISSUE TITLE
Documantation: Incorrectly header variable name for authentication

### ISSUE THREAD

**Issue by codehackefant** [sensebox/openSenseMap#379]
The name of the header variable to use authentication is incorrectly given in the tutorials:

https://en.docs.sensebox.de/opensensemap/opensensemap-security/
https://docs.sensebox.de/opensensemap/opensensemap-security/

The header variable name "**_Authentication_**" doesn't work. The correct variable name is supposed to be "**_Authorization_**".

**Comment by ubergesundheit** [comment]
Thanks for reporting that! It's actually also wrong in the api docs [here](https://docs.opensensemap.org/#api-Measurements-postNewMeasurement) and [here](https://docs.opensensemap.org/#api-Measurements-postNewMeasurements)

@mariopesch can you fix it on sensebox.de?

@felixerdy want to take fixing the api docs?
