### ISSUE TITLE
Website: Link to forum in FAQ section of website not working

### ISSUE THREAD

**Issue by codehackefant** [sensebox/openSenseMap#392]
On the website (https://opensensemap.org) under About -> FAQ there is a link to the forum. Following the link results in the following error:
```
Firefox Can’t Open This Page

To protect your security, forum.sensebox.de will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
```
I guess the link should be changed to open in a new browser window by default. Otherwise inexperienced users might think the forum is broken at all.

Browser: Firefox 84.0

**Comment by ubergesundheit** [comment]
Thanks, in fact, the FAQ is an iframe and the link tries to open inside the iframe. Your suggested solution should fix this.
