### ISSUE TITLE
Improve site performance

### ISSUE THREAD

**Issue by chk1** [sensebox/OpenSenseMap#41]
Graphs and translations make the site work slow, especially on initial load

**Comment by janwirwahn** [comment]
- On initial load: display loading bar if performance cannot be improved

**Comment by chk1** [comment]
Problem is that the browser will simply freeze, I don't think a loading bar is feasible...

For the graphs I have already added a loading indicator, but it doesn't show up most of the time

**Comment by janwirwahn** [comment]
Of course, a loading bar would make no sense for the 'freeze case'. I just recognized that sometimes you must wait for one or two minutes before the location markers show up on the map. For the 'waiting case' i recommend some kind of feedback for the user, e.g. a loading bar.

**Comment by janwirwahn** [comment]
Shorten the time interval of a sensors data when displaying it in the graph view
