### ISSUE TITLE
🔎 Zooming in even further

### ISSUE THREAD

**Issue by nobodyinperson** [sensebox/openSenseMap#436]
### Expected Behavior

Zooming in to precisely see and select senseBoxes that are only a couple meters apart should be possible. 

### Actual Behavior

The maximum zoom level ([`18` apparently](https://github.com/sensebox/openSenseMap/blob/5f114974178c6d3513e42e49b5d7e6b2bd789d83/app/components/leaflet.directive.js#L43)) only allows zooming in this much, making it a really frustrating experience to browse and select close senseBoxes:

![grafik](https://user-images.githubusercontent.com/19148271/158910518-f91e3220-eae4-4009-a8d4-99deb8599319.png)

(Search for the German 'Starzach' city in the search bar, or see [this box](https://opensensemap.org/explore/5d35d315953683001a2b877a))

### Workaround?

Is there a way in the Developer Tools of Firefox (F12) to somehow set this `maxZoom` temporarily? 

### Environment

I'd guess this doesn't depend on the system.

- OS: Manjaro Linux
- Browser & Version: Firefox 96

**Comment by mpfeil** [comment]
Hej @nobodyinperson,

thanks for opening up this issue and you are absolutely right. It is not a nice UX. I will try to deploy a new version of the frontend next week and I will increase the `maxZoom`.

Just to recap: we have set the zoom level to 18 that there is always some information to see on the basemap.

If you want change the `maxZoom` in the Developer Tools you can run the two following statements:
1. `var t = angular.element(document.querySelector('body')).injector().get('osemMapData');`
2. `t.getMap('map_main')["$$state"].value.setMaxZoom(25);`

Hope that helps.

**Comment by nobodyinperson** [comment]
Oh this is awesome thank you for this workaround!!! 🎉🎉🎉
