### ISSUE TITLE
Fix editing an existing box

### ISSUE THREAD

**Issue by chk1** [sensebox/OpenSenseMap#45]
Doesn't work at all right now, includes
- [x] Changing name
- [x] Changing details (which?)
- [x] Changing photo
- [x] Deleting box
- [x] others?

#32

**Comment by chk1** [comment]
API changes required as well
https://github.com/sensebox/OpenSenseMap-API/commit/4cff7c96ebf644c7a059b7c4fc4364ae62696fa8

**Comment by bodensee** [comment]
Photo is still not displayed correctly (broken link). Should this work? It's checked above.

**Comment by chk1** [comment]
It worked at some point... weird, thanks for letting us know

**Comment by janwirwahn** [comment]
Editing may also include change of sensor setup

**Comment by chk1** [comment]
I uploaded a revised version on http://demo.opensensemap.org, editing sensors does not work at this point but I'm working on it. Let me know what you think.

**Comment by bodensee** [comment]
The photos are now displayed. Thank you.
I had a look at the demo. It looks good.

**Comment by chk1** [comment]
It's now done, will be online soon
