### ISSUE TITLE
HTTP (port 80) site returns blank page

### ISSUE THREAD

**Issue by mlgtcode** [sensebox/openSenseMap#478]
### Expected Behavior

Redirect from "http://opensensemap.org/" to  "https://opensensemap.org/", or return content.

### Actual Behavior

The site "http://opensensemap.org/" is not redirecting to "https://opensensemap.org/", just a blank page is returned

**Comment by mpfeil** [comment]
Hi @mlgtcode 

thanks for the request. I have enabled the redirect in our webserver. It will be deployed tomorrow during the day.
