### ISSUE TITLE
apply new webdesign

### ISSUE THREAD

**Issue by robarto** [sensebox/OpenSenseMap#54]
Can you apply the new senseBox design theme to the menu bar:
- logo top left
- fonts in menu
- website icon

**Comment by chk1** [comment]
I changed the icon and "openSenseMap" navbar text font & color for now as shown:
![sensemap](https://cloud.githubusercontent.com/assets/828496/10640258/3f430eec-7814-11e5-8f73-ecd69ce54088.jpg)

A fully green navbar would be too overwhelming I think, I have kept the rest as is for now

**Comment by robarto** [comment]
great thanks! 
maybe the font of openSenseMap in the title bar is bold?

**Comment by mpfeil** [comment]
done
