### ISSUE TITLE
Add SenseBoxID to confirmation email

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/OpenSenseMap#57]
There should be the SenseBoxID specified in the registration confirmation email. The difference between it and the API key should be underlined in the text

**Comment by m-mohr** [comment]
Yes, thats a good idea. I got confused by that and used the API key instead of the SenseboxID. The error returned by the API is also not very good. It states "An error occured" which doesn't help finding the problem at all. The message should be more like "The SenseboxID is wrong" or similar.

**Comment by chk1** [comment]
It is already bold and there's an explanation, I think that's sufficient
