### ISSUE TITLE
Replace green location markers

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/OpenSenseMap#58]
Replace the green with red ones. People are thinking it means "running" and "not running".

**Comment by robarto** [comment]
high priority!

**Comment by robarto** [comment]
delete than the "legend" in the info window...

**Comment by robarto** [comment]
@chk1 kannst du das ggf fix machen? Und wenn du schon am filter bist, kannst du mit der aktualitätsanzeige starten, sodass wir bald sehen könnten, welche senseboxen gerade live sind, noch vor einer woche live waren usw...  das wollten wir ja mit so nem time-slider machen. das wäre cool bald zu haben, weil wir bei den präsentationen immer wild aktive boxen suchen müssen ;)

**Comment by chk1** [comment]
Ja das wird das erste sein was ich einbaue, vorher würde ich noch ein paar strukturelle Sachen umstellen wegen Übersichtlichkeit im Code und so (ui-router Branch)

**Comment by robarto** [comment]
Cool
Am 20.02.2016 4:02 vorm. schrieb "Christoph Kisfeld" <
notifications@github.com>:

**Comment by chk1** [comment]
![firefox_2016-03-03_01-42-15](https://cloud.githubusercontent.com/assets/828496/13480868/2e310bf0-e0e1-11e5-9b72-e029d8024acb.png)

**Comment by janwirwahn** [comment]
Active boxes (green) should not be covered by inactive boxes (grey)

![osem_markers](https://cloud.githubusercontent.com/assets/3083223/14914012/31062768-0e07-11e6-82c9-fd306d034cbf.jpg)
