### ISSUE TITLE
Improve the Hardware setup for custom boxes

### ISSUE THREAD

**Issue by m-mohr** [sensebox/openSenseMap#59]
When registering a custom sensebox there are problems with the sensors.
1. You don't really know what to insert as "Type". There should be a description to explain what the type is or maybe give options to select from.
2. You don't really know what to insert as "Unit". There should be a description to explain what the type is or maybe give options to select from. For example for light, should it be "Lux" or "lx" oder something completely different?
3. If you don't enter anything for type and/or unit you can proceed to the next step and when clicking "Abschließen" it doesn't react at all, without any error message. So you are lost and don't know what to to about it.
4. It would be easier if the checkboxes for "Manuelle Konfiguration" and "senseBox:home mit Ethernet" are automatically selected when the boxes are expanded. You can also continue to the next step without checking one of these boxes.

**Comment by mpfeil** [comment]
There is a description how to setup a custom sensor and what to insert in the single fields.
![description_custom_setup](https://cloud.githubusercontent.com/assets/2471172/20663378/8c51c0a8-b557-11e6-9f8b-83a227dbac43.png)

Teh bugs regarding finishing the setup are fixed.
