### ISSUE TITLE
No Markers visible in india

### ISSUE THREAD

**Issue by robarto** [sensebox/OpenSenseMap#61]
Hi guys,
Shivam jsut told me that he tried to access opensensemap.org from 3 different networks in india (University, company, privat) in different parts of the country. And in any case the markers have shown up. 
Any idea? Seems not to be the known port-problem?

**Comment by chk1** [comment]
I don't really know why it shouldn't work, I will take a look

**Comment by mariopesch** [comment]
I've tried different proxy servers (also from india) and the marker haven't shown up. Maybe it's a port blocking problem?

**Comment by janwirwahn** [comment]
Port 8000 must be open for data communication (GET and POST) with OSeM API. Try to check if you can GET all boxes from http://opensensemap.org:8000/boxes.

**Comment by chk1** [comment]
I will add a subdomain like `api.opensensemap.org` or similar that works on standard port 80 or 443 (https) in the coming weeks after server migration

**Comment by chk1** [comment]
I have added `api.opensensemap.org` now (uses standard port 80), can someone confirm if markers show up on [demo.opensensemap.org](http://demo.opensensemap.org/)?

**Comment by robarto** [comment]
Markers coming in smoothly on Android chrome
Am 09.03.2016 8:52 nachm. schrieb "Christoph Kisfeld" <
notifications@github.com>:
