### ISSUE TITLE
API access not secure

### ISSUE THREAD

**Issue by hdznrrd** [sensebox/openSenseMap#63]
The only information required to post data for any sensor is the sensebox ID and the sensor name.
Both information can be easily scraped from the map site.
With this information a malicious attacker can inject arbitrary data.

To reduce the risk of this happening a simple first step would be adding a shared secret API key token to the request.
For this to work, some kind of transport security will also be needed since currently access to the API is fully plaintext.
For transport encryption see issue #62

**Comment by chk1** [comment]
Thanks

We do have auth tokens for chaning senseBox settings, we could make use of that

This will require updated configs on all the senseBoxes as well

**Comment by mpfeil** [comment]
Newly created devices on openSenseMap are secured with a token. Old devices can be updated using the Edit mode.
The access token was introduced in one of the last API versions.

Check out the `useAuth` parameter: https://docs.opensensemap.org/#api-Boxes-postNewBox
