### ISSUE TITLE
Allow posting of multiple sensor values in a single request

### ISSUE THREAD

**Issue by hdznrrd** [sensebox/OpenSenseMap#64]
As per information I got from Jan the API currently only allows posting a single value per request.
Please allow posting of multiple values from different sensors in a single request.

**Comment by chk1** [comment]
Added new endpoint `/boxes/:boxId/data` which allows posting arrays of json data

https://github.com/sensebox/OpenSenseMap-API/blob/master/app.js#L557-L567
