### ISSUE TITLE
No sensor data accessible?

### ISSUE THREAD

**Issue by makefu** [sensebox/OpenSenseMap#66]
For some reason i am unable to find ANY reliable Sensor on the sensemap website. Either sensors do not show any data at all ( http://opensensemap.org/#/explore/5636334ab3de1fe005ea99f8 ) or the sensors have extremely old data like from 2014 ( http://opensensemap.org/#/explore/538ee6a4a83415541576b777 ).

Is there a way to search for up-to-date and working data?

**Comment by ubergesundheit** [comment]
Check this out https://gist.github.com/ubergesundheit/379d13375ca95b9d62c4
You can use the script to get the boxes with data of the current day

**Comment by chk1** [comment]
I agree that it is a bit difficult to find data right now. We will be removing inactive boxes soon, and also integrate some new features that help you discover recent data.

**Comment by makefu** [comment]
@chk1 thanks for the reply. The outlook indeed sounds very promising. Maybe in the map instead of coloring different hardware models in different color you could color sensor hosts in green which have posted data within the last 24 hours.

I am looking forward to the updates :+1:
