### ISSUE TITLE
Sensor names in OSM box .ino creation script

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/openSenseMap#73]
When setting up a manually configured sense box with more than one temperature sensor, both sensors are assigned the same name (``TEMPSENSOR_ID``) in the mailed sensebox.ino file. Numbering (for example ``TEMPSENSOR2_ID``) would be desirable.

Also, (at least) humidity and light (digital) sensors are named ``SENSOR1_ID`` (here numbering works) with their phenomenon only mentioned in a comment. Naming as done with temperature sensors would be desirable.

**Comment by mpfeil** [comment]
This is an issue of the API. I openend up a new issue here: https://github.com/sensebox/openSenseMap-API/issues/27 For updates check the issue over there.
