### ISSUE TITLE
Icons of measurements on explore site

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/openSenseMap#74]
When in explore mode, on the measurements tab of a box, every sensor has an icon. With my box, all icons are the same (a vertical bar chart icon), except for one (the humidity sensor) being displayed with a "two triangles to right" (looks like a "forward" button on a TV remote control) icon.

Is this on purpose? If yes, a legend should be provided explaining what each icon means.

**Comment by mpfeil** [comment]
WIth PR #106 you can change the icons of your sensors in edit mode or during the registration.
