### ISSUE TITLE
Behaviour during Manage mode

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/OpenSenseMap#77]
If one enters Manage mode (by inserting a valid API key into the box) but doesn't finish managing through clicking either Save or Cancel (i.e. just disregards that tab and continues browsing the site), clicking on sense box markers doesn't work as expected (box title remains an input box).

To fix this and avoid confusion in general, I'd suggest to remove the Manage tab and replace it with a lightbox/dialog UI that pops up when clicking a Manage link -- usually sense boxes aren't managed too often anyways :-)

**Comment by chk1** [comment]
Moved it into a modal, should work better now
