### ISSUE TITLE
Localization not fully in effect and not remembered

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/openSenseMap#78]
- Manage tab doesn't get localized (remains German when switching from German to English)
- Locale setting isn't remembered upon reloading or opening in new tab
- [tiny] "Download sketch" button reads "Sketch erunterladen" (missing "h") in German - but the de_DE.json locale file on Github is OK. Very weird.

**Comment by chk1** [comment]
Fixed the typo

**Comment by christophfriedrich** [comment]
Meanwhile, the manage tab (now manage window) gets localized too, so bullet points 1 and 3 are fixed. New instances of the OSeM in the same browser remain unlocalized.

However, translation on first page load doesn't work in Firefox. The country is recognized (I see a German flag in the upper right corner), but (almost) all text remains Enlish. When switching to another language and back, everything works fine, so it must be the initial trigger. Tested in Firefox 46.0.1. Everything works fine in Chrome.

Also, dates in the measurements tab remain in the silly M/D/Y 12h format regardless of what language you choose, which is annoying for everyone but Americans... IMO: Either localize dates too or just use the universal YYYY-MM-DD HH:MM format for everyone.

**Comment by ubergesundheit** [comment]
Which OS are you using?

**Comment by christophfriedrich** [comment]
Windows 10 Home 64bit

**Comment by mpfeil** [comment]
Dates in the measurements are now localized. see commit c5919304abe14f3af3aad34f1c0beeca8981b97e

**Comment by mpfeil** [comment]
@christophfriedrich: we tested the app on different windows systems and the initial load works.

- Firefox 44 - 47 on Windows 10
- Firefox 46 and 47 on Windows 8.1

Please check if it is working on your system. If not please come around and we can check it on your device.
