### ISSUE TITLE
Embed SVG into own website

### ISSUE THREAD

**Issue by niccokunzmann** [sensebox/openSenseMap#79]
There are SVGs generated at http://opensensemap.org/#/explore/5719c4037514d05c121e317c
Is it possible to embed them into a web page? It would be great if this could just be a tag.

Could you show me how and where you generate these SVG files?

**Comment by niccokunzmann** [comment]
I have found what you are using: http://www.highcharts.com/demo/line-basic/grid-light

**Comment by chk1** [comment]
These SVGs are generated client-side with Highcharts, as you have already discovered.

I have switched these charts to [C3](http://c3js.org/) in the newer version of OpenSenseMap.

You can query the API for the newest Sensebox data like this and build your own charts:

http://demoapi.opensensemap.org/boxes/5719c4037514d05c121e317c/data/5719c4037514d05c121e3182?from-date=&to-date=2016-04-22T09:45:04.619Z

5719c4037514d05c121e317c = your Sensebox ID
5719c4037514d05c121e3182 = your temperature sensor ID

If you need help let me know

**Comment by niccokunzmann** [comment]
I created an HTML file to show the statistics [here](http://rawgit.com/HPIMakerKlub/sensebox/master/statistics/sensor.html?senseBoxID=5719c4037514d05c121e317c). [Repository](https://github.com/HPIMakerKlub/sensebox).

The goal should be something like

    <embed id="embed" src="http://.../sensebox.svg?senseBoxIDs=5719c4037514d05c121e317c,...&width=...&height=...&sensors=5719c4037514d05c121e3182,..." type="image/svg+xml">

This would allow anyone to integrate their and regional senseboxes into a website.

**Comment by ubergesundheit** [comment]
Another option would be to use the openSenseMap-widget
https://sensebox.de/opensensemap-widget

Closing this now
