### ISSUE TITLE
Uploading box image doesn't work

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/openSenseMap#81]
I tried to upload a picture of my sensebox but saving it doesn't work.

What I did: insert API key on the Manage tab, click Edit, switch to Information tab, select a file, switch back to Manage tab and click Save.

What happened: The default image on the information tab disappeared, being replaced with `http://opensensemap.org/userimages/57062bcb45fd40c81974667e.jpeg`. But requesting that file only returns a 404 error, i.e. I guess the uploading process doesn't work properly.

System used: Windows 7 running latest Firefox 45.0.2. Using the latest Chrome 50 didn't work either.

**Comment by chk1** [comment]
Sorry it is broken on the website right now, will be fixed later today, images are saved in the wrong place... I will move it to the right place

**Comment by ubergesundheit** [comment]
Should be working now
