### ISSUE TITLE
Prioritize active markers on the map

### ISSUE THREAD

**Issue by chk1** [sensebox/OpenSenseMap#84]
Active markers should be on top of inactive markers, https://github.com/sensebox/OpenSenseMap/issues/58#issuecomment-215681073

The rendering routine can be changed to reflect this with the zIndex property, see http://leafletjs.com/reference.html#marker-setzindexoffset

Other ideas: Clustering, or some other form of map/marker display

**Comment by ubergesundheit** [comment]
Fixed by @noerw in https://github.com/sensebox/OpenSenseMap/commit/59f0c095fd2c692e1122a995c6eb06de4c51f2fb
