### ISSUE TITLE
Delete/manipulate sample data

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/openSenseMap#85]
I received several requests from users about how they can delete some of their measurements from their initial indoor tests. To address that, we should either create something like a test mode on the server for the SenseBox setup, or the possibility enable a user to delete (parts of) his/her data.

**Comment by m-mohr** [comment]
I do support this request. Deleting and creating a new box all the time is annoying. Probably a button to delete all previously recorded data would be helpful for many users.

**Comment by mpfeil** [comment]
@ubergesundheit can you add a function to the API to delete all recorded data

**Comment by ubergesundheit** [comment]
done

**Comment by mpfeil** [comment]
also see https://github.com/sensebox/openSenseMap-API/issues/93

**Comment by mpfeil** [comment]
Now its possible to delete all measurements of for a specific timeframe
