### ISSUE TITLE
Data download seems to not work

### ISSUE THREAD

**Issue by robarto** [sensebox/openSenseMap#86]
Von Frank Oliver:

Was mir gerade aufgefallen ist, man kann keine Daten mehr von der SenseMap herunterladen.
Er tut als ob, aber es kommt kein CSV File zum abspeichern.
Habe es mit verschiedenen Zeiträumen, Stationen und Sensoren probiert.
Auch mit Firefox und Internet Explorer.
Leider nix...

![osem_download](https://cloud.githubusercontent.com/assets/3996475/15462376/be91aa08-20c2-11e6-9d8b-66c67283e077.png)

**Comment by chk1** [comment]
Hm ich kann da ein paar mögliche Fehlerquellen sehen:
- Server überlastet, liefert einfach nix zurück, sollte aber auf der Seite Feedback geben ("keine Daten") oder sowas
- Die Downloadfunktion lädt die Daten zunächst in den Browsercache und bietet am Ende den Download an, vielleicht wird das nicht unterstützt bei manchen Konfigurationen? Oder einfach zu viele Daten? Konnte selbst nur auf Chrome und Firefox [Stand April] auf Windows 7 testen
- Irgendein API Bug oder komische Daten in der Datenbank

**Comment by ubergesundheit** [comment]
Gestern getestet:
Windows 10, Chrome 50.0.2661.75 m -> Funktioniert
Windows 10, Firefox 45.0.2 -> Funktioniert nicht. Scheint als würden die Parameter für den download nicht richtig an die API übergeben werden..

**Comment by ubergesundheit** [comment]
Download now works in Chrome and Firefox. Fixed as per f898b1c and https://github.com/sensebox/docker-caddy/commit/20c0ddcce9838127d01516970d72250ff08e87e3
