### ISSUE TITLE
alert "OpenCPU connection failed"

### ISSUE THREAD

**Issue by noerw** [sensebox/OpenSenseMap#88]
Sometimes on pageload an alert is displayed: "Connection to OpenCPU failed: error"

![screenshot](http://image.prntscr.com/image/04808dbbaea345808faaeffbf6c793d3.png)

This occured sometimes in firefox (ubuntu15) and safari (osx), not yet in chrome.

**Comment by ubergesundheit** [comment]
fixed in production for now. No commit available as it required changing the opencpu library. We will create a fork of it in the future and fix it there.
