### ISSUE TITLE
Accessing OSM via HTTPS fails

### ISSUE THREAD

**Issue by hdznrrd** [sensebox/OpenSenseMap#92]
When accessing OpenSenseMap via HTTPS it doesn't load data.

14:02:25.352 Blocked loading mixed active content "http://opensensemap.org:9000/boxes?date=&phenomenon="1 angular.js:11442:6

To get around this, first ensure that the service on port 9000 allows HTTPS.
Then use a protocol relative link "//opensensemap.org:9000".

The proper way of fixing this, would actually be to redirect any non HTTPS queries to HTTPS and no longer support plaintext communication.

**Comment by ubergesundheit** [comment]
Thanks for openinig the issue.
We are currently working on a solution to fully supporting tls encrypted communication for both the page and the api.
For now, you have to be a little patient. HTTPS is coming soon.

**Comment by ubergesundheit** [comment]
The page and api is now accessible over https
