### ISSUE TITLE
Map tiles are fetched via HTTP when accessing OSM via HTTPS

### ISSUE THREAD

**Issue by hdznrrd** [sensebox/OpenSenseMap#93]
14:02:25.373 Loading mixed (insecure) display content "http://otile3.mqcdn.com/tiles/1.0.0/map/6/33/21.jpeg" on a secure page1 leaflet-src.js:2928:17

otile3.mqcdn.com supports HTTPS, though the certificate used there is only covering a bunch of different akamai hosts, not otile3.mqcdn.com. Therefore it causes a certificate warning...

Either way, to dynamically reference otile with either http or https use a protocol relative URL:
"//otile3.mqcdn.com" instead of "https://otile3.mqcdn.com" or "http://otile3.mqcdn.com".

Ideally, forbid plaintext access entirely and redirect everyone to an HTTPS-only version of the website.

**Comment by ubergesundheit** [comment]
Thanks. See my answer [here](https://github.com/sensebox/OpenSenseMap/issues/92#issuecomment-223273470)
