### ISSUE TITLE
Check HighCharts compatibility with OSeM license

### ISSUE THREAD

**Issue by m-mohr** [sensebox/OpenSenseMap#94]
As far as I know HighCharts, which is used by this project, is not compatible with the MIT license, see https://shop.highsoft.com/faq#Non-Commercial-0 for more information. To avoid any licensing problems, you should check that. I think you would need to use another library.

**Comment by mpfeil** [comment]
HighCharts is not used anymore. It was replaced by [C3.js](http://c3js.org/) with commit cd7d84f8b059121ded3aea4ab2b19b644471458e

[C3.js](http://c3js.org/) is licensed under MIT. https://github.com/c3js/c3/blob/master/LICENSE

HighCharts is still in the bower dependencies. @ubergesundheit could you remove the dependencies?
