### ISSUE TITLE
Maximum map zoom level doesn't load

### ISSUE THREAD

**Issue by christophfriedrich** [sensebox/OpenSenseMap#95]
When one clicks on a sensebox marker and the map zooms in all the way to that position, the map tiles are not rendered. Instead, one only sees the marker on a grey background. When one then zooms out one step, the tiles are displayed perfectly fine, when one zooms in again, they're not. I.e. it appears that the map tiles don't support that high of a zoom level.

**Comment by ubergesundheit** [comment]
We changed to https tiles. These do not support zoom level 18. Please delete your cache and try again

**Comment by christophfriedrich** [comment]
Deleted cache and tried again but the problem still occurs. :/

**Comment by ubergesundheit** [comment]
Please open http://opensensemap.org/scripts/controllers/map.js with your browser and verify line 13 `maxZoom: 17`. If not hard-reload with Ctrl+F5.

**Comment by christophfriedrich** [comment]
Ok, it was indeed a chaching error, despite clearing the cache in the browser settings... Opening the js file directly in the browser did the proper reload, it works now as expected.
