### ISSUE TITLE
Hintergrundkarte: MapQuest tiles sind nicht mehr frei nutzbar

### ISSUE THREAD

**Issue by chk1** [sensebox/openSenseMap#98]
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

https://lists.openstreetmap.org/pipermail/tile-serving/2016-June/003928.html

**Comment by ubergesundheit** [comment]
Thanks @chk1

**Comment by mpfeil** [comment]
was closed with commit 996b821bd65f96b18940e7a3a46c3743c7446c23
